# Generated by Django 3.1.5 on 2021-01-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifa', models.CharField(max_length=54)),
                ('is_dhaka', models.BooleanField(default=False)),
                ('is_sylhet', models.BooleanField(default=False)),
                ('is_khulna', models.BooleanField(default=False)),
                ('is_male', models.BooleanField(default=False)),
                ('is_female', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['is_dhaka'], name='filter_filt_is_dhak_4b965c_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['is_sylhet'], name='filter_filt_is_sylh_513f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['is_khulna'], name='filter_filt_is_khul_f2cfbf_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['is_male'], name='filter_filt_is_male_6a1258_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['is_female'], name='filter_filt_is_fema_a3a9c9_idx'),
        ),
    ]
