# Generated by Django 3.1.5 on 2021-01-13 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filter',
            name='filter_filt_is_sylh_513f6a_idx',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='is_sylhet',
        ),
        migrations.AddField(
            model_name='filter',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
